### ISSUE TITLE
i cant using one parameter.

### ISSUE THREAD

**Issue by TapXWorld** [scottkiss/grtm#2]
`package main
import (
	"fmt"
	"github.com/scottkiss/grtm"
	"time"
)
func main() {
	gm := grtm.NewGrManager()

	gm.NewGoroutine("func", test, "hello")

	time.Sleep(time.Second * 5000)
}

func test(str string) {
	fmt.Println(str)
}`

**Comment by TapXWorld** [comment]
GOROOT=D:\Go #gosetup
GOPATH=D:\GOPATH #gosetup
D:\Go\bin\go.exe build -i -o C:\Users\whoami\AppData\Local\Temp\___go_build_Test_go.exe D:/GOPATH/src/pageThread/Test.go #gosetup
"D:\Program Files\JetBrains\GoLand 2017.3\bin\runnerw.exe" C:\Users\whoami\AppData\Local\Temp\___go_build_Test_go.exe #gosetup
panic: interface conversion: interface {} is func(string), not func(interface {})

goroutine 18 [running]:
github.com/scottkiss/grtm.(*GrManager).NewGoroutine.func1(0xc042072018, 0x4ecb4e, 0x4, 0x4ecb4e, 0x4, 0x4cb1c0, 0x4f4d58, 0xc0420481c0, 0x1, 0x1)
	D:/GOPATH/src/github.com/scottkiss/grtm/grmanager.go:73 +0x20a
created by github.com/scottkiss/grtm.(*GrManager).NewGoroutine
	D:/GOPATH/src/github.com/scottkiss/grtm/grmanager.go:64 +0xac

**Comment by PearceDuan** [comment]
I met same problem... do you resolve this?

**Comment by xxiaocheng** [comment]
You can define your function like this:
```
func test(str interface{}) {
fmt.Println(str.(string))
}
```
